// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void carcircle_Animation(lv_obj_t * TargetObject, int delay);
void zuoyou_Animation(lv_obj_t * TargetObject, int delay);
void circle2_Animation(lv_obj_t * TargetObject, int delay);
void tiaodo_Animation(lv_obj_t * TargetObject, int delay);
void tingzhi_Animation(lv_obj_t * TargetObject, int delay);
void zhuanquan_Animation(lv_obj_t * TargetObject, int delay);
void shansuo_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image10;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label1;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label8;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label9;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label4;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label7;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image15;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image22;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Keyboard1;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage2;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_TabPage3;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Image35;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Panel1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Keyboard2;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Image8;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Label17;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Keyboard4;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image11;
void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image24;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label20;
void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Image27;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Container2;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image28;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image30;
void ui_event_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Image33;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_703041396);    // assets/主页背景.png
LV_IMG_DECLARE(ui_img_491042716);    // assets/天气背景-4.png
LV_IMG_DECLARE(ui_img_1208922968);    // assets/小车.png
LV_IMG_DECLARE(ui_img_540878956);    // assets/登录头像.png
LV_IMG_DECLARE(ui_img_1454264222);    // assets/时间背景.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_62174538);    // assets/向下按钮.png
LV_IMG_DECLARE(ui_img_1630288244);    // assets/语音背景.png
LV_IMG_DECLARE(ui_img_1874886367);    // assets/音乐背景.png
LV_IMG_DECLARE(ui_img_2096567455);    // assets/转盘.png
LV_IMG_DECLARE(ui_img_1232115273);    // assets/视频背景.png
LV_IMG_DECLARE(ui_img_604655580);    // assets/流量背景.png
LV_IMG_DECLARE(ui_img_1615747111);    // assets/SOS背景.png
LV_IMG_DECLARE(ui_img_50470853);    // assets/导航背景-4.png
LV_IMG_DECLARE(ui_img_1858872258);    // assets/相机3.13.png
LV_IMG_DECLARE(ui_img_756801193);    // assets/行车记录背景.png
LV_IMG_DECLARE(ui_img_1971172720);    // assets/视频集.png
LV_IMG_DECLARE(ui_img_1656314145);    // assets/座椅块3.13 (3).png
LV_IMG_DECLARE(ui_img_1643313576);    // assets/电风扇3.13.png
LV_IMG_DECLARE(ui_img_342436176);    // assets/空调3.13).png
LV_IMG_DECLARE(ui_img_1286555028);    // assets/语音闪烁.png
LV_IMG_DECLARE(ui_img_1761638915);    // assets/sos框图片6.png
LV_IMG_DECLARE(ui_img_84290273);    // assets/登录界面.png
LV_IMG_DECLARE(ui_img_2096174455);    // assets/返回3.13).png
LV_IMG_DECLARE(ui_img_1749208717);    // assets/座椅加热png.png
LV_IMG_DECLARE(ui_img_465780092);    // assets/座椅3.13.png
LV_IMG_DECLARE(ui_img_2078435346);    // assets/取消3.13.png
LV_IMG_DECLARE(ui_img_1389980420);    // assets/相册背景.png
LV_IMG_DECLARE(ui_img_1332689492);    // assets/视屏背景png.png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui_img_11_png);    // assets/11.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_14_png);    // assets/14.png
LV_IMG_DECLARE(ui_img_15_png);    // assets/15.png
LV_IMG_DECLARE(ui_img_16_png);    // assets/16.png
LV_IMG_DECLARE(ui_img_17_png);    // assets/17.png
LV_IMG_DECLARE(ui_img_18_png);    // assets/18.png
LV_IMG_DECLARE(ui_img_19_png);    // assets/19.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_20_png);    // assets/20.png
LV_IMG_DECLARE(ui_img_21_png);    // assets/21.png
LV_IMG_DECLARE(ui_img_22_png);    // assets/22.png
LV_IMG_DECLARE(ui_img_23_png);    // assets/23.png
LV_IMG_DECLARE(ui_img_24_png);    // assets/24.png
LV_IMG_DECLARE(ui_img_25_png);    // assets/25.png
LV_IMG_DECLARE(ui_img_26_png);    // assets/26.png
LV_IMG_DECLARE(ui_img_27_png);    // assets/27.png
LV_IMG_DECLARE(ui_img_28_png);    // assets/28.png
LV_IMG_DECLARE(ui_img_29_png);    // assets/29.png
LV_IMG_DECLARE(ui_img_30_png);    // assets/30.png
LV_IMG_DECLARE(ui_img_31_png);    // assets/31.png
LV_IMG_DECLARE(ui_img_32_png);    // assets/32.png
LV_IMG_DECLARE(ui_img_33_png);    // assets/33.png
LV_IMG_DECLARE(ui_img_34_png);    // assets/34.png
LV_IMG_DECLARE(ui_img_35_png);    // assets/35.png
LV_IMG_DECLARE(ui_img_36_png);    // assets/36.png
LV_IMG_DECLARE(ui_img_37_png);    // assets/37.png
LV_IMG_DECLARE(ui_img_38_png);    // assets/38.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_9_png);    // assets/9.png
LV_IMG_DECLARE(ui_img_537786332);    // assets/座椅-4.png
LV_IMG_DECLARE(ui_img_1759290867);    // assets/座椅2.png
LV_IMG_DECLARE(ui_img_886354412);    // assets/相册-4.png
LV_IMG_DECLARE(ui_img_1603563022);    // assets/语音图标-3.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font1mid);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Fontb30);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
