// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void * openaifuction(void *arg);
void openmusicfuction(lv_event_t * e);
void openvideo(lv_event_t * e);
void opendaohang(lv_event_t * e);
void openSOSfuction(lv_event_t * e);
void openbmps(lv_event_t * e);
void openshipin(lv_event_t * e);
void fasongxiaoxi(lv_event_t * e);
void get_code(lv_event_t * e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
