// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_1749208717, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image24, &ui_img_2096174455);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image24, -319);
    lv_obj_set_y(ui_Image24, 217);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image24, 29);

    ui_Button3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button3, 135);
    lv_obj_set_height(ui_Button3, 38);
    lv_obj_set_x(ui_Button3, -317);
    lv_obj_set_y(ui_Button3, 216);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -318);
    lv_obj_set_y(ui_Label20, 218);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Fontb30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Screen4);
    lv_slider_set_mode(ui_Slider4, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 150);
    lv_obj_set_height(ui_Slider4, 23);
    lv_obj_set_x(ui_Slider4, -184);
    lv_obj_set_y(ui_Slider4, -26);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Slider4, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider4, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x4F7C79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Slider4, lv_color_hex(0xFF4040), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Slider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Slider4, false, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -329);
    lv_obj_set_y(ui_Label22, -146);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "主驾驶位");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Fontb30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image25, &ui_img_465780092);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image25, -339);
    lv_obj_set_y(ui_Image25, 115);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_Image25, 180);
    lv_obj_set_style_img_recolor(ui_Image25, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image25, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image26 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image26, &ui_img_465780092);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image26, -337);
    lv_obj_set_y(ui_Image26, -58);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_Image26, 180);
    lv_obj_set_style_bg_grad_color(ui_Image26, lv_color_hex(0xF90202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Image26, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Image26, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Image26, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_clip_corner(ui_Image26, false, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Image26, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Image26, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_Image26, lv_color_hex(0xFF2323), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image26, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_Image26, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_img_recolor_opa(ui_Image26, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image27 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image27, &ui_img_2078435346);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image27, -194);
    lv_obj_set_y(ui_Image27, -75);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image27, 60);

    ui_Button22 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button22, 63);
    lv_obj_set_height(ui_Button22, 50);
    lv_obj_set_x(ui_Button22, -192);
    lv_obj_set_y(ui_Button22, -77);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_Screen4);
    lv_slider_set_mode(ui_Slider2, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 23);
    lv_obj_set_x(ui_Slider2, -191);
    lv_obj_set_y(ui_Slider2, 127);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Slider2, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x4F7C79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Slider2, lv_color_hex(0xFF4040), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Slider2, false, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button24 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button24, 63);
    lv_obj_set_height(ui_Button24, 50);
    lv_obj_set_x(ui_Button24, -197);
    lv_obj_set_y(ui_Button24, 83);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image29, &ui_img_2078435346);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image29, -197);
    lv_obj_set_y(ui_Image29, 84);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image29, 60);

    ui_Label24 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -331);
    lv_obj_set_y(ui_Label24, 29);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "左后座位");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Fontb30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image28, &ui_img_465780092);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image28, 336);
    lv_obj_set_y(ui_Image28, 115);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image28, 180);
    lv_obj_set_style_img_recolor(ui_Image28, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image28, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Slider3 = lv_slider_create(ui_Screen4);
    lv_slider_set_mode(ui_Slider3, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 150);
    lv_obj_set_height(ui_Slider3, 23);
    lv_obj_set_x(ui_Slider3, 204);
    lv_obj_set_y(ui_Slider3, 129);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Slider3, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider3, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x4F7C79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Slider3, lv_color_hex(0xFF4040), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Slider3, false, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button25 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button25, 63);
    lv_obj_set_height(ui_Button25, 50);
    lv_obj_set_x(ui_Button25, 200);
    lv_obj_set_y(ui_Button25, 81);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image31, &ui_img_2078435346);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image31, 200);
    lv_obj_set_y(ui_Image31, 82);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image31, 60);

    ui_Image30 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image30, &ui_img_465780092);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image30, 339);
    lv_obj_set_y(ui_Image30, -57);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_zoom(ui_Image30, 180);
    lv_obj_set_style_img_recolor(ui_Image30, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image30, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Slider5 = lv_slider_create(ui_Screen4);
    lv_slider_set_mode(ui_Slider5, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 150);
    lv_obj_set_height(ui_Slider5, 23);
    lv_obj_set_x(ui_Slider5, 202);
    lv_obj_set_y(ui_Slider5, -27);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Slider5, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider5, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x4F7C79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Slider5, lv_color_hex(0xFF4040), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Slider5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Slider5, false, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image33 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image33, &ui_img_2078435346);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image33, 198);
    lv_obj_set_y(ui_Image33, -76);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image33, 60);

    ui_Button26 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button26, 63);
    lv_obj_set_height(ui_Button26, 50);
    lv_obj_set_x(ui_Button26, 199);
    lv_obj_set_y(ui_Button26, -77);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 325);
    lv_obj_set_y(ui_Label25, -149);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "副驾驶位");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Fontb30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 324);
    lv_obj_set_y(ui_Label26, 27);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "右后座位");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_Fontb30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);

}
